### PR TITLE
Correctness / Stability fixes

### PR DESCRIPTION
**Pull request by Ben-Lichtman**
Set of changes which should prevent all the remaining loops and oob indexes yet discovered.

should solve https://github.com/mdsteele/rust-cfb/issues/17, https://github.com/mdsteele/rust-cfb/issues/18, https://github.com/mdsteele/rust-cfb/issues/21 unless more cases are uncovered.

These are just naive changes and alternatives that mesh better with the CFB format are likely possible, as well as further efficiency improvements.

Currently the looping problem is solved using a HashSet in each of the problem areas which checks to see if a sector has already been visited and returns an error if a duplicate is detected.

### CODE REVIEW

**Comment by Ben-Lichtman** [comment]
In the latest commit I replaced the usages of stdlib hasher with the FNV hasher, which should be much faster for small inputs (u32s)

**Comment by mdsteele** [comment]
Thanks for the PR!  The code to avoid cycles all looks reasonable to me.  If you're feeling up for it, it would be great to add some new regression tests to `tests/malformed.rs` for the problems that this fixes (for example using one of the fuzzed files you used to find the problem).

I'm less sure about using `fnv`; in addition to adding another dependency, its crate docs mention that:

> Its disadvantages are that it...provides no protection against collision attacks, where a malicious user can craft specific keys designed to slow a hasher down. Thus, it is important to...be certain that your program could not be exposed to malicious inputs (including being a networked server).

Unless there's profiling evidence to suggest that using `fnv` over the default hasher makes an appreciable difference for `cfb`, I would lean towards sticking with the default.

**Comment by Ben-Lichtman** [comment]
Your concerns are valid, however since the keys to the hashset are a fixed size (u32) the denial of service attacks should not be a problem.

Collisions with only 32bits of input are highly unlikely, even with this less robust hashing algorithm, and if one were to occur it wouldn't really be a problem anyway - just slow it down slightly.

On the other hand, my (admittedly not very scientific) testing shows around a 2x speed up compared to stdlib's hasher.

Stdlib's hasher is cryptographically secure and DoS resistant, which makes it comparatively very slow, and those special properties are not necessary for this specific use case.

**Comment by Ben-Lichtman** [comment]
As for the tests, I'll try making one tomorrow.

**Comment by Ben-Lichtman** [comment]
If you're not comfortable bringing in a new dependency, may I suggest making it optional and feature-gated?

**Comment by mdsteele** [comment]
Gotcha, thanks.  I took another look at the `fnv` crate and realized that it's tiny and doesn't bring in any transitive dependencies, so I guess there's no reason not to use it.  So I don't think the feature-gate is necessary.

I've made almost no effort yet on making the `cfb` crate at all performant, so there's probably lots of low-hanging fruit; maybe this is one of them.  (-:

**Comment by Ben-Lichtman** [comment]
I did my best to add a test for infinite loops - It sets a timeout and panics if the file takes longer than the timeout to open and read.

**Comment by mdsteele** [comment]
Thanks!

**Pull request merged**
